// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using idflNet.Data;

#nullable disable

namespace idflNet.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240224055519_add_language_pagemetadata_data_table")]
    partial class add_language_pagemetadata_data_table
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Core.Models.PageMetaDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Field")
                        .HasColumnType("longtext");

                    b.Property<string>("Key")
                        .HasColumnType("longtext");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Session")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.ToTable("dbpagemetadata", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("20908e5d-ad36-4030-a2ea-1c07f0e243c7"),
                            CreatedAt = new DateTime(2024, 2, 24, 12, 55, 19, 649, DateTimeKind.Local).AddTicks(9864),
                            Field = "header",
                            Key = "home",
                            LanguageId = new Guid("434d7f1c-532b-4e28-9007-61a10098562d"),
                            Session = "sessionService",
                            Value = "CHÚNG TÔI ĐẢM BẢO CHẤT LƯỢNG"
                        },
                        new
                        {
                            Id = new Guid("1f4fda1a-89c1-4f19-bc96-e95efc7de576"),
                            CreatedAt = new DateTime(2024, 2, 24, 12, 55, 19, 649, DateTimeKind.Local).AddTicks(9867),
                            Field = "header",
                            Key = "home",
                            LanguageId = new Guid("f8d5b292-35e8-4ebc-8e94-cc10bbbad127"),
                            Session = "sessionService",
                            Value = "WE GUARANTEE QUALITY"
                        },
                        new
                        {
                            Id = new Guid("543e4f85-cdab-4b45-81ba-3c94405cd25b"),
                            CreatedAt = new DateTime(2024, 2, 24, 12, 55, 19, 649, DateTimeKind.Local).AddTicks(9869),
                            Field = "subHeader",
                            Key = "home",
                            LanguageId = new Guid("434d7f1c-532b-4e28-9007-61a10098562d"),
                            Session = "sessionService",
                            Value = "DFL tiến hành kiểm tra tại chỗ và xem xét tài liệu để xác minh khả năng truy xuất nguồn gốc của nhà cung cấp và các yếu tố xã hội, hóa học, môi trường và phúc lợi động vật. Nhấp vào bên dưới để tìm hiểu chi tiết về từng chứng nhận kiểm toán do IDFL cung cấp."
                        },
                        new
                        {
                            Id = new Guid("f58e1736-b012-4cb7-a98c-658b72107e29"),
                            CreatedAt = new DateTime(2024, 2, 24, 12, 55, 19, 649, DateTimeKind.Local).AddTicks(9871),
                            Field = "subHeader",
                            Key = "home",
                            LanguageId = new Guid("f8d5b292-35e8-4ebc-8e94-cc10bbbad127"),
                            Session = "sessionService",
                            Value = "DFL conducts on-site audits, and documentation reviews to verify supplier traceability and social, chemical, environmental and animal welfare. Click below to learn details about each of the audit certifications offered by IDFL."
                        });
                });

            modelBuilder.Entity("Core.Models.UserModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("dbuser", (string)null);
                });

            modelBuilder.Entity("idflNet.Core.Models.BaseModel.LanguageModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Code")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("dblanguage", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("434d7f1c-532b-4e28-9007-61a10098562d"),
                            Code = "vi",
                            CreatedAt = new DateTime(2024, 2, 24, 12, 55, 19, 649, DateTimeKind.Local).AddTicks(9817),
                            IsActive = true,
                            Name = "Tiếng việt"
                        },
                        new
                        {
                            Id = new Guid("f8d5b292-35e8-4ebc-8e94-cc10bbbad127"),
                            Code = "en",
                            CreatedAt = new DateTime(2024, 2, 24, 12, 55, 19, 649, DateTimeKind.Local).AddTicks(9839),
                            IsActive = true,
                            Name = "English"
                        });
                });

            modelBuilder.Entity("idflNet.Core.Models.BaseModel.UserClientInformationModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<string>("City")
                        .HasColumnType("longtext");

                    b.Property<string>("CompanyName")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("District")
                        .HasColumnType("longtext");

                    b.Property<string>("Dob")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Ward")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("dbuserclient", (string)null);
                });

            modelBuilder.Entity("Core.Models.PageMetaDataModel", b =>
                {
                    b.HasOne("idflNet.Core.Models.BaseModel.LanguageModel", "LanguageModel")
                        .WithMany("PageMetaDataModels")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_language_pagemetadata");

                    b.Navigation("LanguageModel");
                });

            modelBuilder.Entity("idflNet.Core.Models.BaseModel.UserClientInformationModel", b =>
                {
                    b.HasOne("Core.Models.UserModel", "UserModel")
                        .WithMany("UserClientInformationModels")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_userInfo");

                    b.Navigation("UserModel");
                });

            modelBuilder.Entity("Core.Models.UserModel", b =>
                {
                    b.Navigation("UserClientInformationModels");
                });

            modelBuilder.Entity("idflNet.Core.Models.BaseModel.LanguageModel", b =>
                {
                    b.Navigation("PageMetaDataModels");
                });
#pragma warning restore 612, 618
        }
    }
}
