// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using idflNet.Data;

#nullable disable

namespace idflNet.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240229074427_add_category_standard_media_data_table")]
    partial class add_category_standard_media_data_table
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Core.Models.BannerHomePageModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Url")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("dbbannerhomepage", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("15f479bf-a4a7-48cd-85c6-7517912531ec"),
                            CreatedAt = new DateTime(2024, 2, 29, 14, 44, 27, 73, DateTimeKind.Local).AddTicks(5588),
                            Url = ""
                        },
                        new
                        {
                            Id = new Guid("4532a5ab-7c56-42a5-9e39-2bc4f05ca59c"),
                            CreatedAt = new DateTime(2024, 2, 29, 14, 44, 27, 73, DateTimeKind.Local).AddTicks(5673),
                            Url = ""
                        },
                        new
                        {
                            Id = new Guid("dab1928f-3bf4-4a85-b3f4-0d37dbbf907b"),
                            CreatedAt = new DateTime(2024, 2, 29, 14, 44, 27, 73, DateTimeKind.Local).AddTicks(5723),
                            Url = ""
                        });
                });

            modelBuilder.Entity("Core.Models.MediaModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Url")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("dbmedia", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("1630c65e-8e63-48dc-8229-b6501399f4c9"),
                            CreatedAt = new DateTime(2024, 2, 29, 14, 44, 27, 73, DateTimeKind.Local).AddTicks(6155),
                            Url = ""
                        },
                        new
                        {
                            Id = new Guid("327e708a-d2d7-4dc9-aadb-acaa569800ae"),
                            CreatedAt = new DateTime(2024, 2, 29, 14, 44, 27, 73, DateTimeKind.Local).AddTicks(6193),
                            Url = ""
                        },
                        new
                        {
                            Id = new Guid("9b20c7ee-45e2-409f-b0a6-8c8b879e7b5d"),
                            CreatedAt = new DateTime(2024, 2, 29, 14, 44, 27, 73, DateTimeKind.Local).AddTicks(6233),
                            Url = ""
                        },
                        new
                        {
                            Id = new Guid("02b44015-0e08-48b6-960c-74d6514f61d2"),
                            CreatedAt = new DateTime(2024, 2, 29, 14, 44, 27, 73, DateTimeKind.Local).AddTicks(6273),
                            Url = ""
                        },
                        new
                        {
                            Id = new Guid("415f020d-3168-427c-a6f4-7d04745828ee"),
                            CreatedAt = new DateTime(2024, 2, 29, 14, 44, 27, 73, DateTimeKind.Local).AddTicks(6350),
                            Url = ""
                        },
                        new
                        {
                            Id = new Guid("ac4019d7-e899-46c7-ae3f-b2079d032fe2"),
                            CreatedAt = new DateTime(2024, 2, 29, 14, 44, 27, 73, DateTimeKind.Local).AddTicks(6410),
                            Url = ""
                        },
                        new
                        {
                            Id = new Guid("333c35fc-8f84-4fcc-9907-d8c563a8ef59"),
                            CreatedAt = new DateTime(2024, 2, 29, 14, 44, 27, 73, DateTimeKind.Local).AddTicks(6447),
                            Url = ""
                        });
                });

            modelBuilder.Entity("idflNet.Core.Models.BaseModel.UserClientInformationModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<string>("City")
                        .HasColumnType("longtext");

                    b.Property<string>("CompanyName")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("District")
                        .HasColumnType("longtext");

                    b.Property<string>("Dob")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Ward")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("dbuserclient", (string)null);
                });

            modelBuilder.Entity("idflNet.Core.Models.CategoryModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Thumbnail")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.ToTable("dbcategory", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("21ccff1c-48fc-419c-a8b2-9d3df4b748b4"),
                            CreatedAt = new DateTime(2024, 2, 29, 14, 44, 27, 73, DateTimeKind.Local).AddTicks(5867),
                            Description = "",
                            IsActive = true,
                            LanguageId = new Guid("07cc6b31-f1cc-4e6c-9ed8-5ffa389d3fe7"),
                            Name = "GLOBAL RECYLED STANDARD",
                            Thumbnail = ""
                        },
                        new
                        {
                            Id = new Guid("44be8122-6b69-4826-822d-4fa867ff4f7e"),
                            CreatedAt = new DateTime(2024, 2, 29, 14, 44, 27, 73, DateTimeKind.Local).AddTicks(5831),
                            Description = "",
                            IsActive = true,
                            LanguageId = new Guid("aff66bad-a320-4ce5-8215-1ae09adb4f5e"),
                            Name = "TIÊU CHUẨN TÁI CHẾ TOÀN CẦU",
                            Thumbnail = ""
                        },
                        new
                        {
                            Id = new Guid("a49ff7f6-0c47-4a13-83c2-8d8e2a4cf905"),
                            CreatedAt = new DateTime(2024, 2, 29, 14, 44, 27, 73, DateTimeKind.Local).AddTicks(5921),
                            Description = "",
                            IsActive = true,
                            LanguageId = new Guid("aff66bad-a320-4ce5-8215-1ae09adb4f5e"),
                            Name = "TIÊU CHUẨN DỆT HỮU CƠ TOÀN CẦU",
                            Thumbnail = ""
                        },
                        new
                        {
                            Id = new Guid("7a2c8b69-926e-45a5-8308-eb65da7f7f0c"),
                            CreatedAt = new DateTime(2024, 2, 29, 14, 44, 27, 73, DateTimeKind.Local).AddTicks(5959),
                            Description = "",
                            IsActive = true,
                            LanguageId = new Guid("07cc6b31-f1cc-4e6c-9ed8-5ffa389d3fe7"),
                            Name = "GLOBAL ORGANIC TEXTILE STANDARD",
                            Thumbnail = ""
                        },
                        new
                        {
                            Id = new Guid("2a36bad6-9ace-463a-ba5c-e64c521875c8"),
                            CreatedAt = new DateTime(2024, 2, 29, 14, 44, 27, 73, DateTimeKind.Local).AddTicks(6039),
                            Description = "",
                            IsActive = true,
                            LanguageId = new Guid("07cc6b31-f1cc-4e6c-9ed8-5ffa389d3fe7"),
                            Name = "RESPONSIBLE WOOL STANDARD",
                            Thumbnail = ""
                        },
                        new
                        {
                            Id = new Guid("c49e4206-663f-4726-8b4c-5d5db64391dc"),
                            CreatedAt = new DateTime(2024, 2, 29, 14, 44, 27, 73, DateTimeKind.Local).AddTicks(5993),
                            Description = "",
                            IsActive = true,
                            LanguageId = new Guid("aff66bad-a320-4ce5-8215-1ae09adb4f5e"),
                            Name = "TIÊU CHUẨN LEN CÓ TRÁCH NHIỆM",
                            Thumbnail = ""
                        });
                });

            modelBuilder.Entity("idflNet.Core.Models.LanguageModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Code")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("dblanguage", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aff66bad-a320-4ce5-8215-1ae09adb4f5e"),
                            Code = "vi",
                            CreatedAt = new DateTime(2024, 2, 29, 14, 44, 27, 73, DateTimeKind.Local).AddTicks(4610),
                            IsActive = true,
                            Name = "Tiếng việt"
                        },
                        new
                        {
                            Id = new Guid("07cc6b31-f1cc-4e6c-9ed8-5ffa389d3fe7"),
                            Code = "en",
                            CreatedAt = new DateTime(2024, 2, 29, 14, 44, 27, 73, DateTimeKind.Local).AddTicks(4631),
                            IsActive = true,
                            Name = "English"
                        });
                });

            modelBuilder.Entity("idflNet.Core.Models.PageMetaDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Field")
                        .HasColumnType("longtext");

                    b.Property<string>("Key")
                        .HasColumnType("longtext");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Session")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.ToTable("dbpagemetadata", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("7fc54a62-aa8c-4344-aa01-f3ce9b1cf956"),
                            CreatedAt = new DateTime(2024, 2, 29, 14, 44, 27, 73, DateTimeKind.Local).AddTicks(4688),
                            Field = "header",
                            Key = "home",
                            LanguageId = new Guid("aff66bad-a320-4ce5-8215-1ae09adb4f5e"),
                            Session = "sessionService",
                            Value = "CHÚNG TÔI ĐẢM BẢO CHẤT LƯỢNG"
                        },
                        new
                        {
                            Id = new Guid("6a4e07a4-5c1e-4682-8b65-c335d0aa8277"),
                            CreatedAt = new DateTime(2024, 2, 29, 14, 44, 27, 73, DateTimeKind.Local).AddTicks(4691),
                            Field = "header",
                            Key = "home",
                            LanguageId = new Guid("07cc6b31-f1cc-4e6c-9ed8-5ffa389d3fe7"),
                            Session = "sessionService",
                            Value = "WE GUARANTEE QUALITY"
                        },
                        new
                        {
                            Id = new Guid("28aa00a8-046c-4d39-a5e3-e3c61a372db9"),
                            CreatedAt = new DateTime(2024, 2, 29, 14, 44, 27, 73, DateTimeKind.Local).AddTicks(4693),
                            Field = "subHeader",
                            Key = "home",
                            LanguageId = new Guid("aff66bad-a320-4ce5-8215-1ae09adb4f5e"),
                            Session = "sessionService",
                            Value = "DFL tiến hành kiểm tra tại chỗ và xem xét tài liệu để xác minh khả năng truy xuất nguồn gốc của nhà cung cấp và các yếu tố xã hội, hóa học, môi trường và phúc lợi động vật. Nhấp vào bên dưới để tìm hiểu chi tiết về từng chứng nhận kiểm toán do IDFL cung cấp."
                        },
                        new
                        {
                            Id = new Guid("84168072-1e98-4baf-959c-5328c0ca43d7"),
                            CreatedAt = new DateTime(2024, 2, 29, 14, 44, 27, 73, DateTimeKind.Local).AddTicks(4695),
                            Field = "subHeader",
                            Key = "home",
                            LanguageId = new Guid("07cc6b31-f1cc-4e6c-9ed8-5ffa389d3fe7"),
                            Session = "sessionService",
                            Value = "DFL conducts on-site audits, and documentation reviews to verify supplier traceability and social, chemical, environmental and animal welfare. Click below to learn details about each of the audit certifications offered by IDFL."
                        });
                });

            modelBuilder.Entity("idflNet.Core.Models.StandardModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("MediaId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("LanguageId");

                    b.HasIndex("MediaId");

                    b.ToTable("dbstandard", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("72f40d80-7f1c-4979-af04-a545ea943a08"),
                            CategoryId = new Guid("44be8122-6b69-4826-822d-4fa867ff4f7e"),
                            Description = "<p>Ti&ecirc;u chuẩn c&oacute; s&aacute;u mục ti&ecirc;u: (1) điều chỉnh c&aacute;c định nghĩa về &quot;t&aacute;i chế&quot; tr&ecirc;n nhiều ứng dụng, (2) theo d&otilde;i v&agrave; truy t&igrave;m nguy&ecirc;n liệu đầu v&agrave;o được t&aacute;i chế, (3) cung cấp cho kh&aacute;ch h&agrave;ng c&ocirc;ng cụ để đưa ra quyết định s&aacute;ng suốt, (4) giảm t&aacute;c động c&oacute; hại của sản xuất dựa tr&ecirc;n con người v&agrave; m&ocirc;i trường, (5) đảm bảo rằng vật liệu trong sản phẩm cuối c&ugrave;ng được t&aacute;i chế v&agrave; xử l&yacute; bền vững v&agrave; (6) th&uacute;c đẩy đổi mới trong việc giải quyết c&aacute;c vấn đề chất lượng li&ecirc;n quan đến việc sử dụng vật liệu t&aacute;i chế.</p>\n                <p><strong>Phạm vi</strong><br />\n                Người nộp đơn c&oacute; thể chọn loại vật liệu t&aacute;i chế m&agrave; họ muốn kiểm to&aacute;n. C&aacute;c vật liệu t&aacute;i chế phổ biến bao gồm l&ocirc;ng tơ v&agrave; l&ocirc;ng vũ, PET, d&acirc;y t&oacute;c, sợi/chỉ v&agrave; vải. C&aacute;c c&ocirc;ng ty đăng k&yacute;, chẳng hạn như c&aacute;c thương hiệu v&agrave; nh&agrave; sản xuất, c&oacute; thể chọn sản phẩm cuối c&ugrave;ng m&agrave; họ muốn đ&aacute;nh gi&aacute;. Một danh s&aacute;ch đầy đủ c&aacute;c sản phẩm v&agrave; danh mục sản phẩm c&oacute; thể được t&igrave;m thấy ở đ&acirc;y.</p>\n                <p><strong>Y&ecirc;u cầu</strong><br />\n                C&aacute;c vật liệu v&agrave; sản phẩm được lựa chọn sẽ được đ&aacute;nh gi&aacute; dựa tr&ecirc;n y&ecirc;u cầu trong c&aacute;c lĩnh vực sau:<br />\n                T&aacute;i chế<br />\n                Chuỗi cung ứng<br />\n                X&atilde; hội<br />\n                Thuộc về m&ocirc;i trường<br />\n                H&oacute;a chất</p>",
                            IsActive = true,
                            LanguageId = new Guid("aff66bad-a320-4ce5-8215-1ae09adb4f5e"),
                            MediaId = new Guid("1630c65e-8e63-48dc-8229-b6501399f4c9"),
                            Name = "Tiêu chuẩn tái chế toàn cầu (GRS)"
                        },
                        new
                        {
                            Id = new Guid("4da04cb1-e39f-445b-b2c6-0ad074919366"),
                            CategoryId = new Guid("21ccff1c-48fc-419c-a8b2-9d3df4b748b4"),
                            Description = "<h3><strong>Aims</strong></h3>\n                <p>The aim of the Global Recycled Standard (GRS) is to increase the use of recycled materials.</p>\n                <p>The Standard has six objectives: (1) aligning definitions of &quot;recycled&quot; across multiple applications, (2) tracking and tracing recycled input materials, (3) providing customers with a tool to make informed decisions, (4) reducing the harmful impact of production on people and the environment, (5) providing assurance that materials in a final product are recycled and processed sustainably and (6) driving innovation in addressing quality issues related to the use of recycled materials.</p>\n                <h3><strong>Scope</strong></h3>\n                <p>Applicants may choose the types of recycled materials they want to have audited. Common recycled materials include down and feathers, PET, filament, yarn/thread and fabric. Applicant companies, such as brands and manufacturers, may select the final products they would like to have audited. A complete list of products and product categories can be found&nbsp;<a href='https://idfl.com/textile-exchange-te-mapping-product-categories-and-product-details/'>here</a>.</p>\n                <h3><strong>Requirements</strong></h3>\n                <p>The selected materials and products will be evaluated based upon requirements in the following areas:</p>\n                <ul>\n                    <li>Recycling</li>\n                    <li>Supply Chain</li>\n                    <li>Social</li>\n                    <li>Environmental</li>\n                    <li>Chemical</li>\n                </ul>",
                            IsActive = true,
                            LanguageId = new Guid("aff66bad-a320-4ce5-8215-1ae09adb4f5e"),
                            MediaId = new Guid("1630c65e-8e63-48dc-8229-b6501399f4c9"),
                            Name = "Global Recycled Standard (GRS)"
                        },
                        new
                        {
                            Id = new Guid("990f5512-b757-4b56-9825-abb614ff5d58"),
                            CategoryId = new Guid("44be8122-6b69-4826-822d-4fa867ff4f7e"),
                            Description = "<p>Ti&ecirc;u chuẩn c&oacute; s&aacute;u mục ti&ecirc;u: (1) điều chỉnh c&aacute;c định nghĩa về &quot;t&aacute;i chế&quot; tr&ecirc;n nhiều ứng dụng, (2) theo d&otilde;i v&agrave; truy t&igrave;m nguy&ecirc;n liệu đầu v&agrave;o được t&aacute;i chế, (3) cung cấp cho kh&aacute;ch h&agrave;ng c&ocirc;ng cụ để đưa ra quyết định s&aacute;ng suốt, (4) giảm t&aacute;c động c&oacute; hại của sản xuất dựa tr&ecirc;n con người v&agrave; m&ocirc;i trường, (5) đảm bảo rằng vật liệu trong sản phẩm cuối c&ugrave;ng được t&aacute;i chế v&agrave; xử l&yacute; bền vững v&agrave; (6) th&uacute;c đẩy đổi mới trong việc giải quyết c&aacute;c vấn đề chất lượng li&ecirc;n quan đến việc sử dụng vật liệu t&aacute;i chế.</p>\n                <p><strong>Phạm vi</strong><br />\n                Người nộp đơn c&oacute; thể chọn loại vật liệu t&aacute;i chế m&agrave; họ muốn kiểm to&aacute;n. C&aacute;c vật liệu t&aacute;i chế phổ biến bao gồm l&ocirc;ng tơ v&agrave; l&ocirc;ng vũ, PET, d&acirc;y t&oacute;c, sợi/chỉ v&agrave; vải. C&aacute;c c&ocirc;ng ty đăng k&yacute;, chẳng hạn như c&aacute;c thương hiệu v&agrave; nh&agrave; sản xuất, c&oacute; thể chọn sản phẩm cuối c&ugrave;ng m&agrave; họ muốn đ&aacute;nh gi&aacute;. Một danh s&aacute;ch đầy đủ c&aacute;c sản phẩm v&agrave; danh mục sản phẩm c&oacute; thể được t&igrave;m thấy ở đ&acirc;y.</p>\n                <p><strong>Y&ecirc;u cầu</strong><br />\n                C&aacute;c vật liệu v&agrave; sản phẩm được lựa chọn sẽ được đ&aacute;nh gi&aacute; dựa tr&ecirc;n y&ecirc;u cầu trong c&aacute;c lĩnh vực sau:<br />\n                T&aacute;i chế<br />\n                Chuỗi cung ứng<br />\n                X&atilde; hội<br />\n                Thuộc về m&ocirc;i trường<br />\n                H&oacute;a chất</p>",
                            IsActive = true,
                            LanguageId = new Guid("aff66bad-a320-4ce5-8215-1ae09adb4f5e"),
                            MediaId = new Guid("327e708a-d2d7-4dc9-aadb-acaa569800ae"),
                            Name = "Tiêu chuẩn tái chế toàn cầu (GRS)"
                        },
                        new
                        {
                            Id = new Guid("dc342bbc-3cff-4a72-902a-d20bcdf6cd8c"),
                            CategoryId = new Guid("21ccff1c-48fc-419c-a8b2-9d3df4b748b4"),
                            Description = "<h3><strong>Aims</strong></h3>\n                <p>The aim of the Global Recycled Standard (GRS) is to increase the use of recycled materials.</p>\n                <p>The Standard has six objectives: (1) aligning definitions of &quot;recycled&quot; across multiple applications, (2) tracking and tracing recycled input materials, (3) providing customers with a tool to make informed decisions, (4) reducing the harmful impact of production on people and the environment, (5) providing assurance that materials in a final product are recycled and processed sustainably and (6) driving innovation in addressing quality issues related to the use of recycled materials.</p>\n                <h3><strong>Scope</strong></h3>\n                <p>Applicants may choose the types of recycled materials they want to have audited. Common recycled materials include down and feathers, PET, filament, yarn/thread and fabric. Applicant companies, such as brands and manufacturers, may select the final products they would like to have audited. A complete list of products and product categories can be found&nbsp;<a href='https://idfl.com/textile-exchange-te-mapping-product-categories-and-product-details/'>here</a>.</p>\n                <h3><strong>Requirements</strong></h3>\n                <p>The selected materials and products will be evaluated based upon requirements in the following areas:</p>\n                <ul>\n                    <li>Recycling</li>\n                    <li>Supply Chain</li>\n                    <li>Social</li>\n                    <li>Environmental</li>\n                    <li>Chemical</li>\n                </ul>",
                            IsActive = true,
                            LanguageId = new Guid("aff66bad-a320-4ce5-8215-1ae09adb4f5e"),
                            MediaId = new Guid("327e708a-d2d7-4dc9-aadb-acaa569800ae"),
                            Name = "Global Recycled Standard (GRS)"
                        },
                        new
                        {
                            Id = new Guid("6a76d0ae-340e-46cc-8075-c464221a62c8"),
                            CategoryId = new Guid("a49ff7f6-0c47-4a13-83c2-8d8e2a4cf905"),
                            Description = "<p>Ti&ecirc;u chuẩn c&oacute; s&aacute;u mục ti&ecirc;u: (1) điều chỉnh c&aacute;c định nghĩa về &quot;t&aacute;i chế&quot; tr&ecirc;n nhiều ứng dụng, (2) theo d&otilde;i v&agrave; truy t&igrave;m nguy&ecirc;n liệu đầu v&agrave;o được t&aacute;i chế, (3) cung cấp cho kh&aacute;ch h&agrave;ng c&ocirc;ng cụ để đưa ra quyết định s&aacute;ng suốt, (4) giảm t&aacute;c động c&oacute; hại của sản xuất dựa tr&ecirc;n con người v&agrave; m&ocirc;i trường, (5) đảm bảo rằng vật liệu trong sản phẩm cuối c&ugrave;ng được t&aacute;i chế v&agrave; xử l&yacute; bền vững v&agrave; (6) th&uacute;c đẩy đổi mới trong việc giải quyết c&aacute;c vấn đề chất lượng li&ecirc;n quan đến việc sử dụng vật liệu t&aacute;i chế.</p>\n                <p><strong>Phạm vi</strong><br />\n                Người nộp đơn c&oacute; thể chọn loại vật liệu t&aacute;i chế m&agrave; họ muốn kiểm to&aacute;n. C&aacute;c vật liệu t&aacute;i chế phổ biến bao gồm l&ocirc;ng tơ v&agrave; l&ocirc;ng vũ, PET, d&acirc;y t&oacute;c, sợi/chỉ v&agrave; vải. C&aacute;c c&ocirc;ng ty đăng k&yacute;, chẳng hạn như c&aacute;c thương hiệu v&agrave; nh&agrave; sản xuất, c&oacute; thể chọn sản phẩm cuối c&ugrave;ng m&agrave; họ muốn đ&aacute;nh gi&aacute;. Một danh s&aacute;ch đầy đủ c&aacute;c sản phẩm v&agrave; danh mục sản phẩm c&oacute; thể được t&igrave;m thấy ở đ&acirc;y.</p>\n                <p><strong>Y&ecirc;u cầu</strong><br />\n                C&aacute;c vật liệu v&agrave; sản phẩm được lựa chọn sẽ được đ&aacute;nh gi&aacute; dựa tr&ecirc;n y&ecirc;u cầu trong c&aacute;c lĩnh vực sau:<br />\n                T&aacute;i chế<br />\n                Chuỗi cung ứng<br />\n                X&atilde; hội<br />\n                Thuộc về m&ocirc;i trường<br />\n                H&oacute;a chất</p>",
                            IsActive = true,
                            LanguageId = new Guid("aff66bad-a320-4ce5-8215-1ae09adb4f5e"),
                            MediaId = new Guid("9b20c7ee-45e2-409f-b0a6-8c8b879e7b5d"),
                            Name = "Tiêu chuẩn tái chế toàn cầu (GRS)"
                        },
                        new
                        {
                            Id = new Guid("153ad832-c576-4dbc-aea3-da2181ea3c61"),
                            CategoryId = new Guid("7a2c8b69-926e-45a5-8308-eb65da7f7f0c"),
                            Description = "<h3><strong>Aims</strong></h3>\n                <p>The aim of the Global Recycled Standard (GRS) is to increase the use of recycled materials.</p>\n                <p>The Standard has six objectives: (1) aligning definitions of &quot;recycled&quot; across multiple applications, (2) tracking and tracing recycled input materials, (3) providing customers with a tool to make informed decisions, (4) reducing the harmful impact of production on people and the environment, (5) providing assurance that materials in a final product are recycled and processed sustainably and (6) driving innovation in addressing quality issues related to the use of recycled materials.</p>\n                <h3><strong>Scope</strong></h3>\n                <p>Applicants may choose the types of recycled materials they want to have audited. Common recycled materials include down and feathers, PET, filament, yarn/thread and fabric. Applicant companies, such as brands and manufacturers, may select the final products they would like to have audited. A complete list of products and product categories can be found&nbsp;<a href='https://idfl.com/textile-exchange-te-mapping-product-categories-and-product-details/'>here</a>.</p>\n                <h3><strong>Requirements</strong></h3>\n                <p>The selected materials and products will be evaluated based upon requirements in the following areas:</p>\n                <ul>\n                    <li>Recycling</li>\n                    <li>Supply Chain</li>\n                    <li>Social</li>\n                    <li>Environmental</li>\n                    <li>Chemical</li>\n                </ul>",
                            IsActive = true,
                            LanguageId = new Guid("07cc6b31-f1cc-4e6c-9ed8-5ffa389d3fe7"),
                            MediaId = new Guid("9b20c7ee-45e2-409f-b0a6-8c8b879e7b5d"),
                            Name = "Global Recycled Standard (GRS)"
                        },
                        new
                        {
                            Id = new Guid("39c55cc1-589c-4347-82d6-664b355b4cdc"),
                            CategoryId = new Guid("a49ff7f6-0c47-4a13-83c2-8d8e2a4cf905"),
                            Description = "<p>Ti&ecirc;u chuẩn c&oacute; s&aacute;u mục ti&ecirc;u: (1) điều chỉnh c&aacute;c định nghĩa về &quot;t&aacute;i chế&quot; tr&ecirc;n nhiều ứng dụng, (2) theo d&otilde;i v&agrave; truy t&igrave;m nguy&ecirc;n liệu đầu v&agrave;o được t&aacute;i chế, (3) cung cấp cho kh&aacute;ch h&agrave;ng c&ocirc;ng cụ để đưa ra quyết định s&aacute;ng suốt, (4) giảm t&aacute;c động c&oacute; hại của sản xuất dựa tr&ecirc;n con người v&agrave; m&ocirc;i trường, (5) đảm bảo rằng vật liệu trong sản phẩm cuối c&ugrave;ng được t&aacute;i chế v&agrave; xử l&yacute; bền vững v&agrave; (6) th&uacute;c đẩy đổi mới trong việc giải quyết c&aacute;c vấn đề chất lượng li&ecirc;n quan đến việc sử dụng vật liệu t&aacute;i chế.</p>\n                <p><strong>Phạm vi</strong><br />\n                Người nộp đơn c&oacute; thể chọn loại vật liệu t&aacute;i chế m&agrave; họ muốn kiểm to&aacute;n. C&aacute;c vật liệu t&aacute;i chế phổ biến bao gồm l&ocirc;ng tơ v&agrave; l&ocirc;ng vũ, PET, d&acirc;y t&oacute;c, sợi/chỉ v&agrave; vải. C&aacute;c c&ocirc;ng ty đăng k&yacute;, chẳng hạn như c&aacute;c thương hiệu v&agrave; nh&agrave; sản xuất, c&oacute; thể chọn sản phẩm cuối c&ugrave;ng m&agrave; họ muốn đ&aacute;nh gi&aacute;. Một danh s&aacute;ch đầy đủ c&aacute;c sản phẩm v&agrave; danh mục sản phẩm c&oacute; thể được t&igrave;m thấy ở đ&acirc;y.</p>\n                <p><strong>Y&ecirc;u cầu</strong><br />\n                C&aacute;c vật liệu v&agrave; sản phẩm được lựa chọn sẽ được đ&aacute;nh gi&aacute; dựa tr&ecirc;n y&ecirc;u cầu trong c&aacute;c lĩnh vực sau:<br />\n                T&aacute;i chế<br />\n                Chuỗi cung ứng<br />\n                X&atilde; hội<br />\n                Thuộc về m&ocirc;i trường<br />\n                H&oacute;a chất</p>",
                            IsActive = true,
                            LanguageId = new Guid("aff66bad-a320-4ce5-8215-1ae09adb4f5e"),
                            MediaId = new Guid("02b44015-0e08-48b6-960c-74d6514f61d2"),
                            Name = "Tiêu chuẩn tái chế toàn cầu (GRS)"
                        },
                        new
                        {
                            Id = new Guid("6f9cc6e6-7d3c-434b-8944-f2dbb34f46a4"),
                            CategoryId = new Guid("7a2c8b69-926e-45a5-8308-eb65da7f7f0c"),
                            Description = "<h3><strong>Aims</strong></h3>\n                <p>The aim of the Global Recycled Standard (GRS) is to increase the use of recycled materials.</p>\n                <p>The Standard has six objectives: (1) aligning definitions of &quot;recycled&quot; across multiple applications, (2) tracking and tracing recycled input materials, (3) providing customers with a tool to make informed decisions, (4) reducing the harmful impact of production on people and the environment, (5) providing assurance that materials in a final product are recycled and processed sustainably and (6) driving innovation in addressing quality issues related to the use of recycled materials.</p>\n                <h3><strong>Scope</strong></h3>\n                <p>Applicants may choose the types of recycled materials they want to have audited. Common recycled materials include down and feathers, PET, filament, yarn/thread and fabric. Applicant companies, such as brands and manufacturers, may select the final products they would like to have audited. A complete list of products and product categories can be found&nbsp;<a href='https://idfl.com/textile-exchange-te-mapping-product-categories-and-product-details/'>here</a>.</p>\n                <h3><strong>Requirements</strong></h3>\n                <p>The selected materials and products will be evaluated based upon requirements in the following areas:</p>\n                <ul>\n                    <li>Recycling</li>\n                    <li>Supply Chain</li>\n                    <li>Social</li>\n                    <li>Environmental</li>\n                    <li>Chemical</li>\n                </ul>",
                            IsActive = true,
                            LanguageId = new Guid("07cc6b31-f1cc-4e6c-9ed8-5ffa389d3fe7"),
                            MediaId = new Guid("02b44015-0e08-48b6-960c-74d6514f61d2"),
                            Name = "Global Recycled Standard (GRS)"
                        },
                        new
                        {
                            Id = new Guid("c9b5a135-6976-4c17-ab48-df68575a8803"),
                            CategoryId = new Guid("c49e4206-663f-4726-8b4c-5d5db64391dc"),
                            Description = "<p>Ti&ecirc;u chuẩn c&oacute; s&aacute;u mục ti&ecirc;u: (1) điều chỉnh c&aacute;c định nghĩa về &quot;t&aacute;i chế&quot; tr&ecirc;n nhiều ứng dụng, (2) theo d&otilde;i v&agrave; truy t&igrave;m nguy&ecirc;n liệu đầu v&agrave;o được t&aacute;i chế, (3) cung cấp cho kh&aacute;ch h&agrave;ng c&ocirc;ng cụ để đưa ra quyết định s&aacute;ng suốt, (4) giảm t&aacute;c động c&oacute; hại của sản xuất dựa tr&ecirc;n con người v&agrave; m&ocirc;i trường, (5) đảm bảo rằng vật liệu trong sản phẩm cuối c&ugrave;ng được t&aacute;i chế v&agrave; xử l&yacute; bền vững v&agrave; (6) th&uacute;c đẩy đổi mới trong việc giải quyết c&aacute;c vấn đề chất lượng li&ecirc;n quan đến việc sử dụng vật liệu t&aacute;i chế.</p>\n                <p><strong>Phạm vi</strong><br />\n                Người nộp đơn c&oacute; thể chọn loại vật liệu t&aacute;i chế m&agrave; họ muốn kiểm to&aacute;n. C&aacute;c vật liệu t&aacute;i chế phổ biến bao gồm l&ocirc;ng tơ v&agrave; l&ocirc;ng vũ, PET, d&acirc;y t&oacute;c, sợi/chỉ v&agrave; vải. C&aacute;c c&ocirc;ng ty đăng k&yacute;, chẳng hạn như c&aacute;c thương hiệu v&agrave; nh&agrave; sản xuất, c&oacute; thể chọn sản phẩm cuối c&ugrave;ng m&agrave; họ muốn đ&aacute;nh gi&aacute;. Một danh s&aacute;ch đầy đủ c&aacute;c sản phẩm v&agrave; danh mục sản phẩm c&oacute; thể được t&igrave;m thấy ở đ&acirc;y.</p>\n                <p><strong>Y&ecirc;u cầu</strong><br />\n                C&aacute;c vật liệu v&agrave; sản phẩm được lựa chọn sẽ được đ&aacute;nh gi&aacute; dựa tr&ecirc;n y&ecirc;u cầu trong c&aacute;c lĩnh vực sau:<br />\n                T&aacute;i chế<br />\n                Chuỗi cung ứng<br />\n                X&atilde; hội<br />\n                Thuộc về m&ocirc;i trường<br />\n                H&oacute;a chất</p>",
                            IsActive = true,
                            LanguageId = new Guid("aff66bad-a320-4ce5-8215-1ae09adb4f5e"),
                            MediaId = new Guid("415f020d-3168-427c-a6f4-7d04745828ee"),
                            Name = "Tiêu chuẩn tái chế toàn cầu (GRS)"
                        },
                        new
                        {
                            Id = new Guid("5ff8d2d3-4eca-481d-b111-e9c0175639dd"),
                            CategoryId = new Guid("2a36bad6-9ace-463a-ba5c-e64c521875c8"),
                            Description = "<h3><strong>Aims</strong></h3>\n                <p>The aim of the Global Recycled Standard (GRS) is to increase the use of recycled materials.</p>\n                <p>The Standard has six objectives: (1) aligning definitions of &quot;recycled&quot; across multiple applications, (2) tracking and tracing recycled input materials, (3) providing customers with a tool to make informed decisions, (4) reducing the harmful impact of production on people and the environment, (5) providing assurance that materials in a final product are recycled and processed sustainably and (6) driving innovation in addressing quality issues related to the use of recycled materials.</p>\n                <h3><strong>Scope</strong></h3>\n                <p>Applicants may choose the types of recycled materials they want to have audited. Common recycled materials include down and feathers, PET, filament, yarn/thread and fabric. Applicant companies, such as brands and manufacturers, may select the final products they would like to have audited. A complete list of products and product categories can be found&nbsp;<a href='https://idfl.com/textile-exchange-te-mapping-product-categories-and-product-details/'>here</a>.</p>\n                <h3><strong>Requirements</strong></h3>\n                <p>The selected materials and products will be evaluated based upon requirements in the following areas:</p>\n                <ul>\n                    <li>Recycling</li>\n                    <li>Supply Chain</li>\n                    <li>Social</li>\n                    <li>Environmental</li>\n                    <li>Chemical</li>\n                </ul>",
                            IsActive = true,
                            LanguageId = new Guid("07cc6b31-f1cc-4e6c-9ed8-5ffa389d3fe7"),
                            MediaId = new Guid("415f020d-3168-427c-a6f4-7d04745828ee"),
                            Name = "Global Recycled Standard (GRS)"
                        },
                        new
                        {
                            Id = new Guid("0615851b-582c-450a-91e2-c79a1e320cdf"),
                            CategoryId = new Guid("c49e4206-663f-4726-8b4c-5d5db64391dc"),
                            Description = "<p>Ti&ecirc;u chuẩn c&oacute; s&aacute;u mục ti&ecirc;u: (1) điều chỉnh c&aacute;c định nghĩa về &quot;t&aacute;i chế&quot; tr&ecirc;n nhiều ứng dụng, (2) theo d&otilde;i v&agrave; truy t&igrave;m nguy&ecirc;n liệu đầu v&agrave;o được t&aacute;i chế, (3) cung cấp cho kh&aacute;ch h&agrave;ng c&ocirc;ng cụ để đưa ra quyết định s&aacute;ng suốt, (4) giảm t&aacute;c động c&oacute; hại của sản xuất dựa tr&ecirc;n con người v&agrave; m&ocirc;i trường, (5) đảm bảo rằng vật liệu trong sản phẩm cuối c&ugrave;ng được t&aacute;i chế v&agrave; xử l&yacute; bền vững v&agrave; (6) th&uacute;c đẩy đổi mới trong việc giải quyết c&aacute;c vấn đề chất lượng li&ecirc;n quan đến việc sử dụng vật liệu t&aacute;i chế.</p>\n                <p><strong>Phạm vi</strong><br />\n                Người nộp đơn c&oacute; thể chọn loại vật liệu t&aacute;i chế m&agrave; họ muốn kiểm to&aacute;n. C&aacute;c vật liệu t&aacute;i chế phổ biến bao gồm l&ocirc;ng tơ v&agrave; l&ocirc;ng vũ, PET, d&acirc;y t&oacute;c, sợi/chỉ v&agrave; vải. C&aacute;c c&ocirc;ng ty đăng k&yacute;, chẳng hạn như c&aacute;c thương hiệu v&agrave; nh&agrave; sản xuất, c&oacute; thể chọn sản phẩm cuối c&ugrave;ng m&agrave; họ muốn đ&aacute;nh gi&aacute;. Một danh s&aacute;ch đầy đủ c&aacute;c sản phẩm v&agrave; danh mục sản phẩm c&oacute; thể được t&igrave;m thấy ở đ&acirc;y.</p>\n                <p><strong>Y&ecirc;u cầu</strong><br />\n                C&aacute;c vật liệu v&agrave; sản phẩm được lựa chọn sẽ được đ&aacute;nh gi&aacute; dựa tr&ecirc;n y&ecirc;u cầu trong c&aacute;c lĩnh vực sau:<br />\n                T&aacute;i chế<br />\n                Chuỗi cung ứng<br />\n                X&atilde; hội<br />\n                Thuộc về m&ocirc;i trường<br />\n                H&oacute;a chất</p>",
                            IsActive = true,
                            LanguageId = new Guid("aff66bad-a320-4ce5-8215-1ae09adb4f5e"),
                            MediaId = new Guid("ac4019d7-e899-46c7-ae3f-b2079d032fe2"),
                            Name = "Tiêu chuẩn tái chế toàn cầu (GRS)"
                        },
                        new
                        {
                            Id = new Guid("68619e6c-77ee-42fe-aecc-e3cee77ae83c"),
                            CategoryId = new Guid("2a36bad6-9ace-463a-ba5c-e64c521875c8"),
                            Description = "<h3><strong>Aims</strong></h3>\n                <p>The aim of the Global Recycled Standard (GRS) is to increase the use of recycled materials.</p>\n                <p>The Standard has six objectives: (1) aligning definitions of &quot;recycled&quot; across multiple applications, (2) tracking and tracing recycled input materials, (3) providing customers with a tool to make informed decisions, (4) reducing the harmful impact of production on people and the environment, (5) providing assurance that materials in a final product are recycled and processed sustainably and (6) driving innovation in addressing quality issues related to the use of recycled materials.</p>\n                <h3><strong>Scope</strong></h3>\n                <p>Applicants may choose the types of recycled materials they want to have audited. Common recycled materials include down and feathers, PET, filament, yarn/thread and fabric. Applicant companies, such as brands and manufacturers, may select the final products they would like to have audited. A complete list of products and product categories can be found&nbsp;<a href='https://idfl.com/textile-exchange-te-mapping-product-categories-and-product-details/'>here</a>.</p>\n                <h3><strong>Requirements</strong></h3>\n                <p>The selected materials and products will be evaluated based upon requirements in the following areas:</p>\n                <ul>\n                    <li>Recycling</li>\n                    <li>Supply Chain</li>\n                    <li>Social</li>\n                    <li>Environmental</li>\n                    <li>Chemical</li>\n                </ul>",
                            IsActive = true,
                            LanguageId = new Guid("07cc6b31-f1cc-4e6c-9ed8-5ffa389d3fe7"),
                            MediaId = new Guid("ac4019d7-e899-46c7-ae3f-b2079d032fe2"),
                            Name = "Global Recycled Standard (GRS)"
                        },
                        new
                        {
                            Id = new Guid("e4103b89-1fbc-4697-bc94-782feac48d93"),
                            CategoryId = new Guid("c49e4206-663f-4726-8b4c-5d5db64391dc"),
                            Description = "<p>Ti&ecirc;u chuẩn c&oacute; s&aacute;u mục ti&ecirc;u: (1) điều chỉnh c&aacute;c định nghĩa về &quot;t&aacute;i chế&quot; tr&ecirc;n nhiều ứng dụng, (2) theo d&otilde;i v&agrave; truy t&igrave;m nguy&ecirc;n liệu đầu v&agrave;o được t&aacute;i chế, (3) cung cấp cho kh&aacute;ch h&agrave;ng c&ocirc;ng cụ để đưa ra quyết định s&aacute;ng suốt, (4) giảm t&aacute;c động c&oacute; hại của sản xuất dựa tr&ecirc;n con người v&agrave; m&ocirc;i trường, (5) đảm bảo rằng vật liệu trong sản phẩm cuối c&ugrave;ng được t&aacute;i chế v&agrave; xử l&yacute; bền vững v&agrave; (6) th&uacute;c đẩy đổi mới trong việc giải quyết c&aacute;c vấn đề chất lượng li&ecirc;n quan đến việc sử dụng vật liệu t&aacute;i chế.</p>\n                <p><strong>Phạm vi</strong><br />\n                Người nộp đơn c&oacute; thể chọn loại vật liệu t&aacute;i chế m&agrave; họ muốn kiểm to&aacute;n. C&aacute;c vật liệu t&aacute;i chế phổ biến bao gồm l&ocirc;ng tơ v&agrave; l&ocirc;ng vũ, PET, d&acirc;y t&oacute;c, sợi/chỉ v&agrave; vải. C&aacute;c c&ocirc;ng ty đăng k&yacute;, chẳng hạn như c&aacute;c thương hiệu v&agrave; nh&agrave; sản xuất, c&oacute; thể chọn sản phẩm cuối c&ugrave;ng m&agrave; họ muốn đ&aacute;nh gi&aacute;. Một danh s&aacute;ch đầy đủ c&aacute;c sản phẩm v&agrave; danh mục sản phẩm c&oacute; thể được t&igrave;m thấy ở đ&acirc;y.</p>\n                <p><strong>Y&ecirc;u cầu</strong><br />\n                C&aacute;c vật liệu v&agrave; sản phẩm được lựa chọn sẽ được đ&aacute;nh gi&aacute; dựa tr&ecirc;n y&ecirc;u cầu trong c&aacute;c lĩnh vực sau:<br />\n                T&aacute;i chế<br />\n                Chuỗi cung ứng<br />\n                X&atilde; hội<br />\n                Thuộc về m&ocirc;i trường<br />\n                H&oacute;a chất</p>",
                            IsActive = true,
                            LanguageId = new Guid("aff66bad-a320-4ce5-8215-1ae09adb4f5e"),
                            MediaId = new Guid("333c35fc-8f84-4fcc-9907-d8c563a8ef59"),
                            Name = "Tiêu chuẩn tái chế toàn cầu (GRS)"
                        },
                        new
                        {
                            Id = new Guid("97c2b96c-06c8-4eaa-8075-066c2d9e6990"),
                            CategoryId = new Guid("2a36bad6-9ace-463a-ba5c-e64c521875c8"),
                            Description = "<h3><strong>Aims</strong></h3>\n                <p>The aim of the Global Recycled Standard (GRS) is to increase the use of recycled materials.</p>\n                <p>The Standard has six objectives: (1) aligning definitions of &quot;recycled&quot; across multiple applications, (2) tracking and tracing recycled input materials, (3) providing customers with a tool to make informed decisions, (4) reducing the harmful impact of production on people and the environment, (5) providing assurance that materials in a final product are recycled and processed sustainably and (6) driving innovation in addressing quality issues related to the use of recycled materials.</p>\n                <h3><strong>Scope</strong></h3>\n                <p>Applicants may choose the types of recycled materials they want to have audited. Common recycled materials include down and feathers, PET, filament, yarn/thread and fabric. Applicant companies, such as brands and manufacturers, may select the final products they would like to have audited. A complete list of products and product categories can be found&nbsp;<a href='https://idfl.com/textile-exchange-te-mapping-product-categories-and-product-details/'>here</a>.</p>\n                <h3><strong>Requirements</strong></h3>\n                <p>The selected materials and products will be evaluated based upon requirements in the following areas:</p>\n                <ul>\n                    <li>Recycling</li>\n                    <li>Supply Chain</li>\n                    <li>Social</li>\n                    <li>Environmental</li>\n                    <li>Chemical</li>\n                </ul>",
                            IsActive = true,
                            LanguageId = new Guid("07cc6b31-f1cc-4e6c-9ed8-5ffa389d3fe7"),
                            MediaId = new Guid("333c35fc-8f84-4fcc-9907-d8c563a8ef59"),
                            Name = "Global Recycled Standard (GRS)"
                        });
                });

            modelBuilder.Entity("idflNet.Core.Models.UserModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Roles")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("dbuser", (string)null);
                });

            modelBuilder.Entity("idflNet.Core.Models.BaseModel.UserClientInformationModel", b =>
                {
                    b.HasOne("idflNet.Core.Models.UserModel", "UserModel")
                        .WithMany("UserClientInformationModels")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_userInfo");

                    b.Navigation("UserModel");
                });

            modelBuilder.Entity("idflNet.Core.Models.CategoryModel", b =>
                {
                    b.HasOne("idflNet.Core.Models.LanguageModel", "LanguageModel")
                        .WithMany("CategoryModels")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_language_category");

                    b.Navigation("LanguageModel");
                });

            modelBuilder.Entity("idflNet.Core.Models.PageMetaDataModel", b =>
                {
                    b.HasOne("idflNet.Core.Models.LanguageModel", "LanguageModel")
                        .WithMany("PageMetaDataModels")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_language_pagemetadata");

                    b.Navigation("LanguageModel");
                });

            modelBuilder.Entity("idflNet.Core.Models.StandardModel", b =>
                {
                    b.HasOne("idflNet.Core.Models.CategoryModel", "CategoryModel")
                        .WithMany("StandardModels")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_category_standard");

                    b.HasOne("idflNet.Core.Models.LanguageModel", "LanguageModel")
                        .WithMany("StandardModels")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_language_standard");

                    b.HasOne("Core.Models.MediaModel", "MediaModel")
                        .WithMany("StandardModels")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_media_product");

                    b.Navigation("CategoryModel");

                    b.Navigation("LanguageModel");

                    b.Navigation("MediaModel");
                });

            modelBuilder.Entity("Core.Models.MediaModel", b =>
                {
                    b.Navigation("StandardModels");
                });

            modelBuilder.Entity("idflNet.Core.Models.CategoryModel", b =>
                {
                    b.Navigation("StandardModels");
                });

            modelBuilder.Entity("idflNet.Core.Models.LanguageModel", b =>
                {
                    b.Navigation("CategoryModels");

                    b.Navigation("PageMetaDataModels");

                    b.Navigation("StandardModels");
                });

            modelBuilder.Entity("idflNet.Core.Models.UserModel", b =>
                {
                    b.Navigation("UserClientInformationModels");
                });
#pragma warning restore 612, 618
        }
    }
}
